baseURL = "https://example.com/"
languageCode = "en-us"
title = "Hugo API Demo"

[outputs]
  page = ["json"]
  home = ["html", "json"]
  section = ["json"]
  taxonomy = ["json"]
  taxonomyTerm = [ "json" ]

[taxonomies]
  sport = "sports"

[permalinks]
  page = "/:section/:title/"
